### ISSUE TITLE
npm run hot explaination.

### ISSUE THREAD

**Issue by atilkan** [laravelista/laravel-mix-without-laravel#1]
What is "`npm run hot`"
Only difference seems that it runs on **webpack-dev-server**
Can you explain it on readme file?
Thanks

**Comment by phaberest** [comment]
It is supposed to work as hot reload, in Laravel I remember it was not working properly a few months ago when I tried to use it. It may work with browsersync as per https://github.com/JeffreyWay/laravel-mix/issues/233

**Comment by mabasic** [comment]
> `npm run hot` - this is complicated to explain and I am not sure that I know exactly how it works, but here it goes. It runs all Mix tasks, but it stays active and watches for changes in your assets. If a change occurs it "updates" only the module which has changed, notifies your application of the change and updates the code in the browser without a refresh. Something like that... very cool!

Taken from [Sublimely Magnificent Laravel Mix](https://laravelista.com/lessons/sublimely-magnificent-laravel-mix)
